"""add middle_name to seller

Revision ID: e650cbdcb5a0
Revises: 50c54d4a92f3
Create Date: 2026-06-05 14:58:25.216763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e650cbdcb5a0'
down_revision: Union[str, Sequence[str], None] = '50c54d4a92f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('middle_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'middle_name')
    # ### end Alembic commands ###
